// <auto-generated />
namespace ConnectusMobileService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class unique_connect_request : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unique_connect_request));
        
        string IMigrationMetadata.Id
        {
            get { return "201509301013179_unique_connect_request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
