//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectusMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectRequests
    {
        public string Id { get; set; }
        public string RequestUserId { get; set; }
        public string ConnectUserId { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
    }
}
