//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectusMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoDetails
    {
        public string UserInfo_Id { get; set; }
        public string JsonInfo { get; set; }
        public string Id { get; set; }
        public short NetworkId { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Networks Networks { get; set; }
        public virtual UserInfoes UserInfoes { get; set; }
    }
}
